# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from enum import Enum

class Operation(Enum):
    ADD = '+'
    SUBTRACT = '-'
    MULTIPLY = '*'
    DIVIDE = '/'

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Cannot divide by zero"
    return x / y

operation_functions = {
    Operation.ADD: add,
    Operation.SUBTRACT: subtract,
    Operation.MULTIPLY: multiply,
    Operation.DIVIDE: divide
}

def main():
    while True:
        try:
            num1 = float(input("Enter the first number: "))
            operation_symbol = input("Enter the operation (+, -, *, /): ")
            num2 = float(input("Enter the second number: "))
        except ValueError:
            print("Invalid input. Please enter a number.")
            continue

        operation = None
        for op in Operation:
            if op.value == operation_symbol:
                operation = op
                break

        if operation is not None:
            operation_func = operation_functions[operation]
            if operation_func == divide:
                result = operation_func(num1, num2)
                if result == "Cannot divide by zero":
                    print(result)
                else:
                    print(f"{num1} {operation.value} {num2} = {result}")
            else:
                print(f"{num1} {operation.value} {num2} = {operation_func(num1, num2)}")
        else:
            print("Invalid operation symbol")

        choice = input("Do you want to perform another calculation? (yes/no): ")
        if choice.lower() != "yes":
            break

    print("Goodbye!")

if __name__ == "__main__":
    main()